language: cpp
compiler: 
  - gcc
  - clang
before_install:
  #install a newer cmake since at this time Travis only has version 2.8.7
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - echo "yes" | sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install g++-4.8 cmake libxml2-dev bison flex zlib1g-dev swig python-dev libedit-dev ncurses-dev
  - sudo apt-get 
script:
  - mkdir build
  - cd build && cmake .. && make -j 2 && cd ../test && PATH=build/bin:$PATH llvm-lit .
os:
  - linux
  