language: cpp
compiler: 
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.8 gcc-4.8 cmake libxml2-dev bison flex zlib1g-dev swig python-dev libedit-dev ncurses-dev
  - export CXX="g++-4.8" CC="gcc-4.8"
script:
  - mkdir build
  - cd build && cmake .. && make && cd .. && PATH=./build/bin:$PATH llvm-lit -q test/
os:
  - linux
  
